inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Bundler/DuplicatedGem:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - Rakefile

Lint/SendWithMixinArgument:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Style/NumericPredicate:
  Exclude:
    - lib/netsnmp.rb

Style/RedundantBegin:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/HashConversion:
  Enabled: false

Performance/MethodObjectAsBlock:
  Enabled: false