module NETSNMP::Core
  # Sets all the constants necessary to recognize from the structures
  module Constants
    MAX_OID_LEN = 128

    # Return values of various send functions
    STAT_SUCCESS        = 0
    STAT_ERROR          = 1
    STAT_TIMEOUT        = 2

    SNMP_VERSION_1 = 0
    SNMP_VERSION_2c = 1
    SNMP_VERSION_3 = 3


    USM_AUTH_KU_LEN = 32
    USM_PRIV_KU_LEN = 32

    # SNMPv3 Security Levels
    SNMP_SEC_LEVEL_NOAUTH = 1
    SNMP_SEC_LEVEL_AUTHNOPRIV = 2
    SNMP_SEC_LEVEL_AUTHPRIV = 3

    # SNMP Errors
    SNMPERR_SUCCESS = (0)
    SNMPERR_GENERR = (-1)
    SNMPERR_BAD_LOCPORT = (-2)
    SNMPERR_BAD_ADDRESS = (-3)
    SNMPERR_BAD_SESSION = (-4)
    SNMPERR_TOO_LONG = (-5)
    SNMPERR_NO_SOCKET = (-6)
    SNMPERR_V2_IN_V1 = (-7)
    SNMPERR_V1_IN_V2 = (-8)
    SNMPERR_BAD_REPEATERS = (-9)
    SNMPERR_BAD_REPETITIONS = (-10)
    SNMPERR_BAD_ASN1_BUILD = (-11)
    SNMPERR_BAD_SENDTO = (-12)
    SNMPERR_BAD_PARSE = (-13)
    SNMPERR_BAD_VERSION = (-14)
    SNMPERR_BAD_SRC_PARTY = (-15)
    SNMPERR_BAD_DST_PARTY = (-16)
    SNMPERR_BAD_CONTEXT = (-17)
    SNMPERR_BAD_COMMUNITY = (-18)
    SNMPERR_NOAUTH_DESPRIV = (-19)
    SNMPERR_BAD_ACL = (-20)
    SNMPERR_BAD_PARTY = (-21)
    SNMPERR_ABORT = (-22)
    SNMPERR_UNKNOWN_PDU = (-23)
    SNMPERR_TIMEOUT = (-24)
    SNMPERR_BAD_RECVFROM = (-25)
    SNMPERR_BAD_ENG_ID = (-26)
    SNMPERR_BAD_SEC_NAME = (-27)
    SNMPERR_BAD_SEC_LEVEL = (-28)
    SNMPERR_ASN_PARSE_ERR = (-29)
    SNMPERR_UNKNOWN_SEC_MODEL = (-30)
    SNMPERR_INVALID_MSG = (-31)
    SNMPERR_UNKNOWN_ENG_ID = (-32)
    SNMPERR_UNKNOWN_USER_NAME = (-33)
    SNMPERR_UNSUPPORTED_SEC_LEVEL = (-34)
    SNMPERR_AUTHENTICATION_FAILURE = (-35)
    SNMPERR_NOT_IN_TIME_WINDOW = (-36)
    SNMPERR_DECRYPTION_ERR = (-37)
    SNMPERR_SC_GENERAL_FAILURE = (-38)
    SNMPERR_SC_NOT_CONFIGURED = (-39)
    SNMPERR_KT_NOT_AVAILABLE = (-40)
    SNMPERR_UNKNOWN_REPORT = (-41)
    SNMPERR_USM_GENERICERROR = (-42)
    SNMPERR_USM_UNKNOWNSECURITYNAME = (-43)
    SNMPERR_USM_UNSUPPORTEDSECURITYLEVEL = (-44)
    SNMPERR_USM_ENCRYPTIONERROR = (-45)
    SNMPERR_USM_AUTHENTICATIONFAILURE = (-46)
    SNMPERR_USM_PARSEERROR = (-47)
    SNMPERR_USM_UNKNOWNENGINEID = (-48)
    SNMPERR_USM_NOTINTIMEWINDOW = (-49)
    SNMPERR_USM_DECRYPTIONERROR = (-50)
    SNMPERR_NOMIB = (-51)
    SNMPERR_RANGE = (-52)
    SNMPERR_MAX_SUBID = (-53)
    SNMPERR_BAD_SUBID = (-54)
    SNMPERR_LONG_OID = (-55)
    SNMPERR_BAD_NAME = (-56)
    SNMPERR_VALUE = (-57)
    SNMPERR_UNKNOWN_OBJID = (-58)
    SNMPERR_NULL_PDU = (-59)
    SNMPERR_NO_VARS = (-60)
    SNMPERR_VAR_TYPE = (-61)
    SNMPERR_MALLOC = (-62)
    SNMPERR_KRB5 = (-63)
    SNMPERR_PROTOCOL = (-64)
    SNMPERR_OID_NONINCREASING = (-65)
    SNMPERR_MAX = (-65)

    # PDU variable types
    ASN_BOOLEAN         = 0x01
    ASN_INTEGER         = 0x02
    ASN_BIT_STR         = 0x03
    ASN_OCTET_STR       = 0x04
    ASN_NULL            = 0x05
    ASN_OBJECT_ID       = 0x06
    ASN_SEQUENCE        = 0x10
    ASN_SET             = 0x11

    ASN_UNIVERSAL       = 0x00
    ASN_APPLICATION     = 0x40
    ASN_CONTEXT         = 0x80
    ASN_PRIVATE         = 0xC0

    ASN_PRIMITIVE       = 0x00
    ASN_CONSTRUCTOR     = 0x20

    ASN_LONG_LEN        = 0x80
    ASN_EXTENSION_ID    = 0x1F
    ASN_BIT8            = 0x80


    ASN_IPADDRESS   = (ASN_APPLICATION | 0)
    ASN_COUNTER     = (ASN_APPLICATION | 1)
    ASN_GAUGE       = (ASN_APPLICATION | 2)
    ASN_UNSIGNED    = (ASN_APPLICATION | 2)   # RFC 1902 - same as GAUGE
    ASN_TIMETICKS   = (ASN_APPLICATION | 3)
    ASN_OPAQUE      = (ASN_APPLICATION | 4)
    ASN_NSAP        = (ASN_APPLICATION | 5)  # historic - don't use
    ASN_COUNTER64   = (ASN_APPLICATION | 6)
    ASN_UINTEGER    = (ASN_APPLICATION | 7)   # historic - don't use

    # Exception types for SNMPv2 and SNMPv3 (no value needed)
    SNMP_NOSUCHOBJECT   = (ASN_CONTEXT | ASN_PRIMITIVE | 0x0)
    SNMP_NOSUCHINSTANCE = (ASN_CONTEXT | ASN_PRIMITIVE | 0x1)
    SNMP_ENDOFMIBVIEW   = (ASN_CONTEXT | ASN_PRIMITIVE | 0x2)


    # PDU types
    SNMP_MSG_GET        = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x0)
    SNMP_MSG_GETNEXT    = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x1)
    SNMP_MSG_RESPONSE   = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x2)
    SNMP_MSG_SET        = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x3)
    SNMP_MSG_TRAP       = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x4)
    SNMP_MSG_GETBULK    = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x5)
    SNMP_MSG_INFORM     = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x6)
    SNMP_MSG_TRAP2      = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x7)
    SNMP_MSG_REPORT     = (ASN_CONTEXT | ASN_CONSTRUCTOR | 0x8)


    # Callback status codes
    NETSNMP_CALLBACK_OP_RECEIVED_MESSAGE  =  1
    NETSNMP_CALLBACK_OP_TIMED_OUT         =  2
    NETSNMP_CALLBACK_OP_SEND_FAILED       =  3
    NETSNMP_CALLBACK_OP_CONNECT           =  4
    NETSNMP_CALLBACK_OP_DISCONNECT        =  5

  end
end

