module NETSNMP
  module Loggable
    interface _Debugger
      def <<: (string) -> void
    end

    DEBUG_LEVEL: Integer
    DEBUG: _Debugger
    COLORS: Hash[Symbol, Integer]

    def initialize_logger: (?debug: _Debugger, ?debug_level: Integer, **untyped) -> void

     private

    def log: (?level: Integer) { () -> String } -> void
  end
end
