module NETSNMP
  module Loggable
    interface _Debugger
      def <<: (string) -> void
    end

    DEBUG_LEVEL: Integer
    DEBUG: _Debugger

    private

    def log: (?level: Integer) { () -> String } -> void
  end
end
