module NETSNMP
  module Loggable
    DEBUG_LEVEL: Integer
    DEBUG: IO?
    COLORS: Hash[Symbol, Integer]

    def initialize_logger: (?debug: IO, ?debug_level: Integer, **untyped) -> void

     private

    def log: (?level: Integer) { () -> String } -> void
  end
end
