module NETSNMP
  class Message
    include Loggable

    PRIVNONE: OpenSSL::ASN1::OctetString
    MSG_MAX_SIZE: OpenSSL::ASN1::Integer
    MSG_SECURITY_MODEL: OpenSSL::ASN1::Integer
    MSG_VERSION: OpenSSL::ASN1::Integer
    MSG_REPORTABLE: Integer

    def verify: (String stream, String auth_param, Integer? security_level, security_parameters: SecurityParameters) -> void

    def decode: (String stream, security_parameters: SecurityParameters) -> [ScopedPDU, String, Integer, Integer]

    def encode: (ScopedPDU pdu, security_parameters: SecurityParameters, ?engine_boots: Integer, ?engine_time: Integer, ?require_authentication: bool) -> String

    private

    def initialize: (**untyped options) -> void

    def authnone: (Symbol?, ?bool) -> OpenSSL::ASN1::ASN1Data
  end
end
