# Temporary hack until openssl gets types
module OpenSSL
  module ASN1
    class ASN1Data
      def to_der: () -> String
    end
    class ObjectId < ASN1Data
    end
    class Primitive < ASN1Data
    end
    class Integer < ASN1Data
    end
    class OctetString < ASN1Data
    end
    class Sequence < ASN1Data
    end
  end

  module Digest
    class MD5
      def reset: () -> void
      def <<: (string) -> void
      def digest: () -> String
    end
    class SHA1
      def reset: () -> void
      def <<: (string) -> void
      def digest: () -> String
    end
  end
end

interface _ToAsn
  def to_asn: () -> OpenSSL::ASN1::ASN1Data
end
