module NETSNMP
  class ScopedPDU < PDU
    attr_reader engine_id: String?
    attr_accessor auth_param: String?
    attr_accessor security_level: Integer?

    private

    def initialize: (
      type: Integer,
      ?engine_id: String,
      ?context: String,
      **untyped
    ) -> void

    def encode_headers_asn: () -> [OpenSSL::ASN1::OctetString, OpenSSL::ASN1::OctetString]
  end
end
