module NETSNMP
  class ScopedPDU < PDU
    attr_reader engine_id: String?
    attr_reader auth_param: String?
    attr_reader security_level: Integer?

    private

    def initialize: (
      type: Integer,
      headers: [String?, String?],
      **untyped
    ) -> void

    def encode_headers_asn: () -> [OpenSSL::ASN1::OctetString, OpenSSL::ASN1::OctetString]
  end
end
